################################################################################################################################################################
# This is the main config of DiscoArmor
# Please delete this one after every Update!
# If you find a bug or have a request, please visit the dev page: http://dev.bukkit.org/server-mods/discoarmor
# If you want to help me, donate at http://goo.gl/Z2BST or subscribe to me at Youtube: http://youtube.com/user/LualZockt
################################################################################################################################################################
enable-max-time: false 
max-time: 0

delay: 2 # The delay between switching the colors in ticks. 20 ticks are one second!!!
##########################################################################################################################################################
# Possible options: nothing, armor and wool for the helmet 
##########################################################################################################################################################

armor:
  helmet: armor
  chestplate: armor
  leggings: armor
  boots: armor
names:
  helmet: '&bDiscohelmet'
  chestplate: '&bDiscochestplate'
  leggings: '&bDiscoleggings'
  boots: '&bDiscoboots'
async: false

aliases: # simply define aliases for /da toggle
- superarmor
##############################
# Engine-Modes:
# - 0: Random colors
# - 1: Define colors in the colors-Mode below
##############################
engine-mode: 0 
colors: # RGB format or some predefined colors (see bukkit.dev)
- 255,0,0 # red
- 0,255,0 # green
- 0,0,255 # blue
- 128,128,128 #gray

##############################
messages:
  toggle-true: 'DiscoMode enabled.' # Message when you enable the DiscoArmor mode
  permission-message: '&cYou do not have permission to use DiscoArmor.'
  toggle-false: 'DiscoMode disabled.' # Message when you disable the DiscoArmor mode
  
  
  auto-update-check: true
  
