name: DiscoArmor
version: 2.4.2
author: LualZockt
website: http://dev.bukkit.org/bukkit-plugins/discoarmor
main: de.lualzockt.DiscoArmor.DiscoArmor

commands:
  discoarmor:
    description: Disco Armor
    aliases: [da]
    
    
permissions:
  discoarmor.*:
    description: Gives access to all DiscoArmor commands.
    children:
      discoarmor.toggle: true
      disocarmor.help: true
      discoarmor.info: true
      discoarmor.reload: true
      discoarmor.toggleothers: true
  discoarmor.toggle:
    description: Toggles your DiscoArmor-Mode
  discoarmor.help:
    description: Permission to see the help
    default: true
  discoarmor.info:
    default: true
  discoarmor.toggleothers:
    description: Permission for toggling other players DiscoArmor mode
  
    