name: DiscoArmor
version: 1.6.1
author: LualZockt
website: http://dev.bukkit.org/bukkit-plugins/discoarmor
main: com.lualzockt.DiscoArmor.DiscoArmor

commands:
  discoarmor:
    description: Disco Armor
    aliases: [da]
    
    
permissions:
  discoarmor.*:
    description: All permissions:
    children:
      discoarmor.reload
      discoarmor.toggle
      discoarmor.info
      discoarmor.help
  discoarmor.toggle:
    description: Toggles your DiscoArmor-Mode
  discoarmor.help:
    description: Permission to see the help
    default: true
  discoarmor.info:
    default: true
    